### ISSUE TITLE
z-index issue with multiple magicsuggest/s

### ISSUE THREAD

**Issue by shenghuy** [Magicsuggest/magicsuggest#144]
Hi, 

[tried in latest chrome & firefox]
I have two magicsuggest initialized in one page: say first one is at row 1, and  the other one is at row 2. the layout is like:

magicsuggest_1
magicsuggest_2 

The issue is that: when click on the first magicsuggest, in the dropdown, the magicsuggest_2's input box is displayed.

I tried to manually add a higher z-index to magicsuggest_1, then it behaves properly. However, it's too handy when i have many magicsuggest in a page.

So, my question is : do we have a way to avoid this automatically at the plugin level.

Thanks,
Shenghu

**Comment by z3ugma** [comment]
I'm having the same issue, I think. Here's the html that's causing problems, using Bootstrap:

```<div class="row">
  <div class="col-md-4">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <div class="input-group"><span class="input-group-addon"><i class="fa fa-users"></i><strong>
              Teams</strong></span>
          <input id="ms-filter" class="form-control"/>
        </div>
      </div>
      <div class="panel-body">
        <div id="custom-ctn"></div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <div class="input-group"><span class="input-group-addon"><i class="fa fa-id-card-o"></i><strong>
              Roles</strong></span>
          <input id="ms-role-filter" class="form-control"/>
        </div>
      </div>
    </div>
  </div>
</div>
```

With 2 filters and only when they are wrapped in `.input-group` classes.
![image](https://user-images.githubusercontent.com/6099983/29219331-5092123a-7e7d-11e7-8b27-1636fc5c3dc1.png)

Otherwise, it works fine:

![image](https://user-images.githubusercontent.com/6099983/29219521-ece19462-7e7d-11e7-8529-542d13115f43.png)
