### ISSUE TITLE
Array in value field

### ISSUE THREAD

**Issue by d9cre** [Magicsuggest/magicsuggest#333]
Hi

I want a user to be able to pick a suburb cluster to pick a group of suburbs at once. So the user would pick the cluster "Rosebank and surrounds" and that will be the same as selecting these suburbs "Illovo - GP","Dunkeld West","Dunkeld","Rosebank - GP","Hyde Park - GP".

This is my JSON:

{"name":"Rosebank and surrounds","value":["Illovo - GP","Dunkeld West","Dunkeld","Rosebank - GP","Hyde Park - GP"],"city":"Johannesburg","type":"cluster"}

The magicsuggest plugin won't render the values individually (they are all put into one box in the selectionRenderer) and it won't allow a user to clear the selection without a page refresh (if I render the name as the selectionRenderer).

Can you assist? I've tried a whole bunch of things and nothing has worked. Running another addToSelection function also doesn't work.

Appreciate the help.

**Comment by bhagawatDongre** [comment]
Hi ,

So this is what I understood 
1 ] you have data where 'value' is array of data 

as per my understanding this is not an general case so problem needs to be handled by code who using magicsuggest functionality here.

so you can use object with hashing instead of array where you can either pass object key as value to magicsuggest or stringify() data and pass to magicsuggest so at your end you can parse that object again before using.
