### ISSUE TITLE
trigger update for hidden fields

### ISSUE THREAD

**Issue by al404** [Magicsuggest/magicsuggest#336]
I need to sort magicSuggest elements, I accomplished this with jQuery UI and sortable

$(".tags-container .ms-sel-ctn").sortable({
    cursor: 'move',
    opacity: 0.9,
    axis: 'y',
    update: function(event, ui) {
        console.log("tag sorted");
    }
}).disableSelection();

now I need to fire the update of hidden fields but I can't find how

**Comment by zergioz** [comment]
I suppose you are trying to sort the element before rendering. Try getting the data set already sorted and do all manipulations when serving the data—doing it during rending poses issues depending on the payload.  O(n log n) speeds. 

I am closing this issue because I do not believe this is an issue. 
sort server side
sort when .push() element into array
